# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end

lane :build_deploy do
FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT= 120
  build_app(
    scheme: "HalalApp",
    export_method: "app-store",
    export_xcargs: "-allowProvisioningUpdates"
  )
  upload_to_testflight(
    username: 'nadz.muhd@gmail.com',
  )
end

lane :deploy_test do
  upload_to_testflight(
    username: 'nadz.muhd@gmail.com',
  )
end

lane :icon do
  appicon(appicon_image_file: '../icon/halalApp-icon.png',
             appicon_devices: [:iphone])
end